proyectosproductos:
    pattern:  /posgradmin/proyectosproductos
    defaults: { _controller: ProyectosProductosBundle:ProyectosProductos:index }

_proyectosproductos:
    pattern: /posgradmin/proyectosproductos/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: proyectosproductos}

proyectosproductos_new:
    pattern:  /posgradmin/proyectosproductos/new
    defaults: { _controller: ProyectosProductosBundle:ProyectosProductos:new }

proyectosproductos_edit:
    pattern:  /posgradmin/proyectosproductos/edit/{id}
    defaults: { _controller: ProyectosProductosBundle:ProyectosProductos:edit }

proyectosproductos_delete:
    pattern:  /posgradmin/proyectosproductos/delete/{id}
    defaults: { _controller: ProyectosProductosBundle:ProyectosProductos:delete }