investigadoreslineas:
    pattern:  /posgradmin/investigadoreslineas
    defaults: { _controller: InvestigadoresLineasBundle:InvestigadoresLineas:index }

_investigadoreslineas:
    pattern: /posgradmin/investigadoreslineas/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: investigadoreslineas}

investigadoreslineas_new:
    pattern:  /posgradmin/investigadoreslineas/new
    defaults: { _controller: InvestigadoresLineasBundle:InvestigadoresLineas:new }

investigadoreslineas_edit:
    pattern:  /posgradmin/investigadoreslineas/edit/{id}
    defaults: { _controller: InvestigadoresLineasBundle:InvestigadoresLineas:edit }

investigadoreslineas_delete:
    pattern:  /posgradmin/investigadoreslineas/delete/{id}
    defaults: { _controller: InvestigadoresLineasBundle:InvestigadoresLineas:delete }