noticias:
    pattern:  /posgradmin/noticias
    defaults: { _controller: NoticiasBundle:Noticias:index }

_noticias:
    pattern: /posgradmin/noticias/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: noticias}

noticias_new:
    pattern:  /posgradmin/noticias/new
    defaults: { _controller: NoticiasBundle:Noticias:new }

noticias_edit:
    pattern:  /posgradmin/noticias/edit/{id}
    defaults: { _controller: NoticiasBundle:Noticias:edit }

noticias_delete:
    pattern:  /posgradmin/noticias/delete/{id}
    defaults: { _controller: NoticiasBundle:Noticias:delete }
