alumnos:
    pattern:  /posgradmin/alumnos
    defaults: { _controller: AlumnosBundle:Alumnos:index }

_alumnos:
    pattern: /posgradmin/alumnos/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: alumnos}

alumnos_new:
    pattern:  /posgradmin/alumnos/new
    defaults: { _controller: AlumnosBundle:Alumnos:new }

alumnos_edit:
    pattern:  /posgradmin/alumnos/edit/{id}
    defaults: { _controller: AlumnosBundle:Alumnos:edit }

alumnos_update:
    pattern:  /posgradmin/alumnos/update/{id}
    defaults: { _controller: AlumnosBundle:Alumnos:update }

alumnos_delete:
    pattern:  /posgradmin/alumnos/delete/{id}
    defaults: { _controller: AlumnosBundle:Alumnos:delete }

alumnos_public:
    pattern:  /alumnos
    defaults: { _controller: AlumnosBundle:AlumnosPublic:index }

alumnos_show_public:
    pattern:  /alumnos/show/{id}
    defaults: { _controller: AlumnosBundle:AlumnosPublic:show }
