posgradmin:
    pattern:  /posgradmin
    defaults: { _controller: BackEndBundle:Security:index }

_posgradmin:
    pattern: /posgradmin/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: posgradmin}

fos_user_security_login:
    pattern: /posgradmin/usuario/login
    defaults: { _controller: BackEndBundle:Security:login }

fos_user_security_check:
    pattern: /posgradmin/usuario/login_check
    defaults: { _controller: BackEndBundle:Security:check }

fos_user_security_logout:
    pattern: /posgradmin/usuario/logout
    defaults: { _controller: BackEndBundle:Security:logout }

fos_user_registration_register:
    pattern: /posgradmin/registro
    defaults: { _controller: BackEndBundle:Registration:register }

fos_user_registration_check_email:
    pattern: /posgradmin/checarEmail
    defaults: { _controller: BackEndBundle:Registration:checkEmail }

fos_user_registration_confirm:
    pattern: /posgradmin/confirmar/{token}
    defaults: { _controller: BackEndBundle:Registration:confirm }

fos_user_registration_confirmed:
    pattern: /posgradmin/confirmado
    defaults: { _controller: BackEndBundle:Registration:confirmed }

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile