parameters:
#    investigadores_proyectos.example.class: DEPI\InvestigadoresProyectosBundle\Example

services:
#    investigadores_proyectos.example:
#        class: %investigadores_proyectos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
