investigadores:
    pattern:  /posgradmin/investigadores
    defaults: { _controller: InvestigadoresBundle:Investigadores:index }

_investigadores:
    pattern: /posgradmin/investigadores/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: investigadores}

investigadores_new:
    pattern:  /posgradmin/investigadores/new
    defaults: { _controller: InvestigadoresBundle:Investigadores:new }

investigadores_edit:
    pattern:  /posgradmin/investigadores/edit/{id}
    defaults: { _controller: InvestigadoresBundle:Investigadores:edit }

investigadores_delete:
    pattern:  /posgradmin/investigadores/delete/{id}
    defaults: { _controller: InvestigadoresBundle:Investigadores:delete }

investigadores_public:
    pattern:  /investigadores
    defaults: { _controller: InvestigadoresBundle:InvestigadoresPublic:index }