posgradoareas:
    pattern:  /posgradmin/posgradoareas
    defaults: { _controller: PosgradoAreasBundle:PosgradoAreas:index }

_posgradoareas:
    pattern: /posgradmin/posgradoareas/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: posgradoareas}

posgradoareas_new:
    pattern:  /posgradmin/posgradoareas/new
    defaults: { _controller: PosgradoAreasBundle:PosgradoAreas:new }

posgradoareas_edit:
    pattern:  /posgradmin/posgradoareas/edit/{id}
    defaults: { _controller: PosgradoAreasBundle:PosgradoAreas:edit }