proyectos:
    pattern:  /posgradmin/proyectos
    defaults: { _controller: ProyectosBundle:Proyectos:index }

_proyectos:
    pattern: /posgradmin/proyectos/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: proyectos}

proyectos_new:
    pattern:  /posgradmin/proyectos/new
    defaults: { _controller: ProyectosBundle:Proyectos:new }

proyectos_edit:
    pattern:  /posgradmin/proyectos/edit/{id}
    defaults: { _controller: ProyectosBundle:Proyectos:edit }

proyectos_delete:
    pattern:  /posgradmin/proyectos/delete/{id}
    defaults: { _controller: ProyectosBundle:Proyectos:delete }

proyectos_public:
    pattern:  /proyectos
    defaults: { _controller: ProyectosBundle:ProyectosPublic:index }
