productosacademicos:
    pattern:  /posgradmin/productosacademicos
    defaults: { _controller: ProductosAcademicosBundle:ProductosAcademicos:index }

_productosacademicos:
    pattern: /posgradmin/productosacademicos/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: productosacademicos}

productosacademicos_new:
    pattern:  /posgradmin/productosacademicos/new
    defaults: { _controller: ProductosAcademicosBundle:ProductosAcademicos:new }

productosacademicos_edit:
    pattern:  /posgradmin/productosacademicos/edit/{id}
    defaults: { _controller: ProductosAcademicosBundle:ProductosAcademicos:edit }

productosacademicos_delete:
    pattern:  /posgradmin/productosacademicos/delete/{id}
    defaults: { _controller: ProductosAcademicosBundle:ProductosAcademicos:delete }